type AutoGenerated struct {
	GalleryConfig struct {
		ID          int64       `json:"id"`
		Type        interface{} `json:"type"`
		Name        string      `json:"name"`
		Title       string      `json:"title"`
		Description string      `json:"description"`
		Background  struct {
			Color string `json:"color"`
			Video struct {
				Src  interface{} `json:"src"`
				Size struct {
					W int `json:"w"`
					H int `json:"h"`
				} `json:"size"`
			} `json:"video"`
			Placeholder interface{} `json:"placeholder"`
		} `json:"background"`
		Tags []struct {
			ID    interface{} `json:"id"`
			Label string      `json:"label"`
		} `json:"tags"`
		ItemTypes []interface{} `json:"itemTypes"`
		Debug     bool          `json:"debug"`
	} `json:"galleryConfig"`
	Items []interface{} `json:"items"`
}