type AutoGenerated struct {
	Items []struct {
		ID          int      `json:"id"`
		Parent      int      `json:"parent"`
		Type        string   `json:"type"`
		Description string   `json:"description"`
		Zoom        int      `json:"zoom"`
		Name        string   `json:"name"`
		Title       string   `json:"title"`
		Tags        []string `json:"tags"`
		Thumbnail   struct {
			Align string `json:"align"`
			Size  struct {
				W int `json:"w"`
				H int `json:"h"`
			} `json:"size"`
			Src          string `json:"src"`
			CropStrategy string `json:"cropStrategy"`
			Color        string `json:"color"`
		} `json:"thumbnail"`
		Target struct {
			Size struct {
				W int `json:"w"`
				H int `json:"h"`
			} `json:"size"`
			Src string `json:"src"`
		} `json:"target"`
		Header struct {
			Title string `json:"title"`
			Date  string `json:"date"`
		} `json:"header"`
		Footer struct {
			Title    string `json:"title"`
			Subtitle string `json:"subtitle"`
			Text     string `json:"text"`
			Author   string `json:"author"`
			Date     string `json:"date"`
		} `json:"footer"`
		Background struct {
			Color interface{} `json:"color"`
			Image struct {
				Src  string `json:"src"`
				Size struct {
					W int `json:"w"`
					H int `json:"h"`
				} `json:"size"`
			} `json:"image"`
			Video struct {
				Src  string `json:"src"`
				Size struct {
					W int `json:"w"`
					H int `json:"h"`
				} `json:"size"`
			} `json:"video"`
			Placeholder interface{} `json:"placeholder"`
		} `json:"background"`
		Frame struct {
			Size struct {
				W int `json:"w"`
				H int `json:"h"`
			} `json:"size"`
		} `json:"frame"`
		Hover struct {
			Border      bool `json:"border"`
			Zoom        bool `json:"zoom"`
			Translucent bool `json:"translucent"`
			Overlay     bool `json:"overlay"`
			Banner      bool `json:"banner"`
			Shadow      bool `json:"shadow"`
			OverlayText bool `json:"overlayText"`
		} `json:"hover"`
	} `json:"items"`
}